version: "3.7"

networks:
    cms:
        driver: bridge

# PORTS
# - 4500:Gateway
# - 4501:Dictionary
# - 4502:Users
# - 4503:Pages

services:
    gateway:
        build:
            context: .
            dockerfile: ./Gateway/Gateway/Dockerfile
        ports:
            - 4500:80
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ASPNETCORE_ENVIRONMENT=Development
            - DICTIONARY_URL=http://dictionary:80
            - PAGES_URL=http://pages:80
            - USERS_URL=http://users:80
            - SECURITY_URL=http://security:80
        networks:
            - cms
        depends_on:
            - dictionary
            - users
            - pages
            - security

    dictionary:
        build:
            context: .
            dockerfile: ./Dictionary/API/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "CONNECTION_STRING=${CONNECTION_STRING}"
        networks:
            - cms

    users:
        build:
            context: .
            dockerfile: ./Users/API/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "CONNECTION_STRING=${CONNECTION_STRING}"
        networks:
            - cms

    pages:
        build:
            context: .
            dockerfile: ./Pages/API/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "CONNECTION_STRING=${CONNECTION_STRING}"
        networks:
            - cms

    security:
        build:
            context: .
            dockerfile: ./Security/API/Dockerfile
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "USERS_URL=http://users:80"
        networks:
            - cms
        depends_on:
            - users
